### PR TITLE
fix: use List for Layout types

### PR DESCRIPTION
**Pull request by rchl**
Sequence is a generic type that includes lists, tuples and ranges. In
this case we actually have lists so call it what it is.
The tuples, for example, don't allow some methods like "insert" which
lists allow.

### CODE REVIEW

**Comment by jfcherng** [comment]
Thanks. I haven't played with layout things since I have used ST 😄 .

Looks like I didn't change since I started this repo from 
https://github.com/AmjadHD/sublime_dev/blob/1ece80e896fea9c331394be9f635ecd47823b058/sublime.pyi#L5-L10

---

The following is working in my test.
```py
# set layout to single pane
window.set_layout( {'cells': ((0, 0, 1, 1)), 'cols': (0.0, 1.0), 'rows': (0.0, 1.0)} )
```

It's good to make the returned type annotation as definite as possible. But for parameters like the one in `Window.set_layout`

```py
def set_layout(self, layout: Layout) -> None:
```

The following original one is good for `Window.set_layout`.

```py
class Layout(TypedDict):
    cols: Sequence[float]
    rows: Sequence[float]
    cells: Sequence[Sequence[int]]
```

I guess we need another type for layout parameters like

```py
class Layout_Parameter(TypedDict):
    cols: Sequence[float]
    rows: Sequence[float]
    cells: Sequence[Sequence[int]]


def set_layout(self, layout: Layout_Parameter) -> None:

```

What do you think about this?

**Comment by rchl** [comment]
That suggestion would still not work in my case. In Origami, the layout is retrieved, then the values are mutated using list methods and then set back using set_layout. Having sequence in parameter types would not allow passing the values retrieved from the layout() getter.

Also, the fact that tuples work in this case does not necessarily mean that the intention was to allow them in the API. I don't think they were at least, or the returned layout would also use tuples.

**Comment by jfcherng** [comment]
Yes, after my test. My proposal is not working for types in side a `TypedDict`... Probably because `TypedDict` is not covariant.

**Comment by jfcherng** [comment]
Would you please fix the conflict since I've moved stub files to `typings/`?

**Comment by jfcherng** [comment]
Thanks!

**Pull request merged**
